### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/hrsa/data_AHRF_2018-2019/processed/df_renamed.pkl'

### ISSUE THREAD

**Issue by anonym0305** [Yu-Group/covid19-severity-prediction#1]
Looks like there's a problem with the hrsa data, as below.

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-8-903f57d636ec> in <module>
     15 import load_data
     16 
---> 17 df = load_data.load_county_level()
     18 df = df.sort_values('tot_deaths', ascending=False)
     19 important_vars = load_data.important_keys(df)

~/load_data.py in load_county_level(data_dir, cached_file, cached_file_abridged, ahrf_data, diabetes, voting, icu, heart_disease_data, stroke_data, dir_mod)
     50                                heart_disease_data=heart_disease_data,
     51                                stroke_data=stroke_data,
---> 52                                diabetes=diabetes)  # also cleans usafacts data
     53 
     54     # basic preprocessing

~/functions/merge_data.py in merge_data(ahrf_data, diabetes, voting, icu, heart_disease_data, stroke_data, medicare_group, resp_group)
     18 
     19     # read in data
---> 20     facts = pd.read_pickle(ahrf_data)
     21     facts = facts.rename(columns={'Blank': 'id'})
     22 

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/pickle.py in read_pickle(filepath_or_buffer, compression)
    168     if not isinstance(fp_or_buf, str) and compression == "infer":
    169         compression = None
--> 170     f, fh = get_handle(fp_or_buf, "rb", compression=compression, is_text=False)
    171 
    172     # 1) try standard library Pickle

/srv/conda/envs/notebook/lib/python3.7/site-packages/pandas/io/common.py in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text)
    432         else:
    433             # Binary mode
--> 434             f = open(path_or_buf, mode)
    435         handles.append(f)
    436 

FileNotFoundError: [Errno 2] No such file or directory: 'data/hrsa/data_AHRF_2018-2019/processed/df_renamed.pkl'

**Comment by csinva** [comment]
Thanks for your interest!

The readme should be clearer now - the simplest way to work with this repo is to download the processed pkl file. If you want to download the data sources one by one, you'll have to follow the steps in the `data sources` part of the readme first.

**Comment by anonym0305** [comment]
Hi Chandan - Thanks for answering my query. Looks like the pkl file is pretty large. I'm using a remote server/binder and am unable to upload the file to my github repository. Any suggestions ?

**Comment by csinva** [comment]
The readme can point you to abridged csv files which are smaller and contain the features we think are most relevant:

note: (non-cumulative) daily cases + deaths are in data/usafacts/confirmed_cases.csv and data/usafacts/deaths.csv (updated daily)

note: abridged csv with county-level info such as demographics, hospital information, risk factors, and voting data is at data/df_county_level_abridged_cached.csv

alternatively, you could load the large file, decide for yourself which columns you want to keep and save out a smaller pkl file yourself!
