### ISSUE TITLE
Load dataset code: "Error: No such file"

### ISSUE THREAD

**Issue by royzawadzki** [Yu-Group/covid19-severity-prediction#16]
Per the instructions, I cloned the repo and started a program to run in the root directory:
```
import data
# unabridged
df_unabridged = data.load_county_data(data_dir = "data", cached = False, abridged = False)
```

Running this code produces an error: `FileNotFoundError: [Errno 2] No such file or directory: 'File ../../raw/ahrf_health/ahrf_health.csv does not exist'`. I have been able to reproduce this environment in a totally separate environment. The problem is likely in clean.py. 

Not sure if I'm missing something obvious here.

Other info: MacOS

**Comment by shifwang** [comment]
Hey, thanks for letting us know! I think that's because the file ahrf_health.csv is absent. Could you please try going to the data/county_level/raw/ahrf_health folder and run `python download.py`. If that runs smoothly, that file should be created.

**Comment by shifwang** [comment]
I have also pushed some modifications to ahrf_health clean.py and download.py. So please be sure to use the latest version.

**Comment by royzawadzki** [comment]
> please try going to the data/county_level/raw/ahrf_health folder and run python download.py

Fails to load the sas7bdat, so the error is probably an issue with the source moving locations or something of that sort.

**Comment by shifwang** [comment]
I can run the script with no problem on my end. Have you installed sas7bdat package?

**Comment by shifwang** [comment]
Feel free to let me know if you still have trouble running it, I can also send you the ahrf_health.csv file directly.

**Comment by royzawadzki** [comment]
If it runs fine on your end, then I think its a problem with my environment, I'll go through and see if I have everything installed correctly. Thanks for helping out.

**Comment by Naomi-Ding** [comment]
> Hey, thanks for letting us know! I think that's because the file ahrf_health.csv is absent. Could you please try going to the data/county_level/raw/ahrf_health folder and run python download.py. If that runs smoothly, that file should be created.

@shifwang  I run the file download.py, and then get an Error that  [Errno 2] No such file or directory: 'ahrf2019.sas7bdat'.

**Comment by csinva** [comment]
I think the issue might be that the code requires the `wget` command to automatically download the files, so the raw data might only be retrievable on linux through the current setup.
