### ISSUE TITLE
hospital-level dataset

### ISSUE THREAD

**Issue by Naomi-Ding** [Yu-Group/covid19-severity-prediction#17]
Excuse me, I had trouble while running the script, and got an similar error with #16 . So that I couldn't generate the hospital-level dataset. 
Could you please upload the processed clean hospital-level dataset? Thank you!!

**Comment by Naomi-Ding** [comment]
![image](https://user-images.githubusercontent.com/65834065/82769156-48b1f700-9e01-11ea-9152-f834b8a88bc8.png)
When I run the code to load hospital-level data, it shows above that "Not all the cleaned data is availabel. Halt.".

**Comment by shifwang** [comment]
Sure, I am working on it and will send a link today!

**Comment by Naomi-Ding** [comment]
@shifwang thank you!

**Comment by shifwang** [comment]
This is the link: https://drive.google.com/open?id=1YU21KiL7wQLdkXOcHPu9_oqtLXrRgvkL
