### ISSUE TITLE
Metadata update

### ISSUE THREAD

**Issue by reeshmabijosh** [Yu-Group/covid19-severity-prediction#20]
Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse as a piece of common COVID-19 data frame http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/WB3UE8

Would you be willing to help with the maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for the medical science community.

**Comment by shifwang** [comment]
Hey, thank you for adding our dataset on Dataverse and we would be happy to help maintain it. Could you please give us some guidance on how we should get started?

**Comment by k-goncharova** [comment]
Hello Hue, thank you for your response and willingness to contribute. Please register in CoronaWhy Dataverse https://datasets.coronawhy.org/ and I'll give you the necessary permissions for editing your dataset. Then please add relevant metadata - description and keywords to your dataset. 

Additionally, you may want join our community of 1,000+ contributors in Slack https://www.coronawhy.org/join-the-fight and see if any other initiatives could be interesting to you. We have many cool people and interesting things going on :)
