### ISSUE TITLE
Fail to download the raw dataset

### ISSUE THREAD

**Issue by clin366** [Yu-Group/covid19-severity-prediction#37]
Hi, thanks for sharing this dataset. I'm trying to load the safegraph_socialdistancing data from this git repository. However, it shows that (as shown below) the dataset are stored in a seperated "covid-19-private-data". Is there any way I could get access to this safegraph_socialdistancing data? 

def load_safegraph_socialdistancing(data_dir='../../../../../covid-19-private-data'):
    ''' Load in SafeGraph Social Distancing data (automatically updated)
    
    Parameters
    ----------
    data_dir : str; path to the data directory to find safegraph_socialdistancing.gz (private data)
    
    Returns
    -------
    data frame
    '''
    
    orig_dir = os.getcwd()
    os.chdir(data_dir)

    # refresh and load in data
    os.system("git pull")
    raw = pd.read_pickle("safegraph_socialdistancing.gz", compression="gzip")

**Comment by shifwang** [comment]
Hi @clin366 Thank you for your interest in our repo! Unfortunately, we cannot share safegraph directly because their data is proprietary. You can go checkout their website and request access there.
