### ISSUE TITLE
FIPS code 00001 in usafacts_infections

### ISSUE THREAD

**Issue by SteveGoldstein** [Yu-Group/covid19-severity-prediction#4]
The line in usafacts_infections with FIPS code 00001 corresponds to this line in the raw file:
`1,New York City Unallocated/Probable,NY`
Do you really want it in the processed file?

**Comment by shifwang** [comment]
We keep it so that if later we need to combine it with other NYC counties, the info is still there. It should also be easy to just drop this row if it is not useful.
