### ISSUE TITLE
FIPS code 06000 in usafacts_infections

### ISSUE THREAD

**Issue by SteveGoldstein** [Yu-Group/covid19-severity-prediction#5]
The line in usafacts_infections with FIPS code 06000 corresponds to this line in the raw file:
`6000,Grand Princess Cruise Ship,CA`
Do you really want it in the processed county-level file?

**Comment by shifwang** [comment]
Thanks for letting us know about this! We should remove this.

**Comment by shifwang** [comment]
Fixed.
