### ISSUE TITLE
20069,Gray County,KS has 1 case in processed/usafacts_infections but none in raw

### ISSUE THREAD

**Issue by SteveGoldstein** [Yu-Group/covid19-severity-prediction#6]
tips code 20069 has one case in the processed usafacts_infection column #Cases_04-19-2020 but none in the raw file.  The raw file I'm looking at has entries up to and including  4/20/20.

**Comment by shifwang** [comment]
I updated the usafacts data and right not I did not see 1 case at processed/usafacts_infections anymore. Maybe that's due to an earlier version of usafacts that reported one case then later removed it.
