### ISSUE TITLE
consistency between usafacts and nytimes

### ISSUE THREAD

**Issue by SteveGoldstein** [Yu-Group/covid19-severity-prediction#7]
If a goal is to put county_level data from various source in a common format then consider:

1. Sorting the columns so that the columns in usafacts_infection and nytimes_infections are in the same order.  Currently, the #Cases_<DATE> columns come before the #Deaths_<DATE> in usafacts and the reverse is true for nytimes_infections.

2.  All the numbers in nytimes_infections end in ".0"   e.g.  0.0,0.0,1.0,1.0,...  They are integers in usafacts_infections.    I suggest removing the .0 in the nytimes_infections.

**Comment by shifwang** [comment]
Thank you for the suggestions and those are fixed.
